[package]
name = "nistrs"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Sergey Negodyaev <negodyaev.sergey@outlook.com>"]
description = "This crate implements statistical tests according to the NIST standard"
readme = "README.md"
repository = "https://github.com/Omnissi/NISTRS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.15"
statrs = "0.18.0"
rayon = "1.11.0"
cfg-if = "1.0.4"
rustfft = "6.4.1"

[features]
const_fn_floating_point_arithmetic = []